### ISSUE TITLE
using sei-testnet in NetworkConfigs throws error

### ISSUE THREAD

**Issue by TheSnakeWitcher** [Fusyona/web3-core#38]
Try to configure sei networks in hardhat using the `NetworkConfigs` class and it will throw the following error

```
An unexpected error occurred:

TypeError: Cannot read properties of undefined (reading 'match')
    at NetworkConfig.rpcUrlApiKeyMatches (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/@fusyona+web3-core@0.4.14/node_modules/@fusyona/web3-core/dist/lib/config.js:57:23)
    at NetworkConfig.rpcUrlNeedsApiKey (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/@fusyona+web3-core@0.4.14/node_modules/@fusyona/web3-core/dist/lib/config.js:48:21)
    at NetworkConfig.useRpcUrl (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/@fusyona+web3-core@0.4.14/node_modules/@fusyona/web3-core/dist/lib/config.js:22:19)
    at new NetworkConfig (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/@fusyona+web3-core@0.4.14/node_modules/@fusyona/web3-core/dist/lib/config.js:12:28)
    at NetworkConfigs.networkConfig (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/@fusyona+web3-core@0.4.14/node_modules/@fusyona/web3-core/dist/lib/config.js:95:16)
    at NetworkConfigs.network (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/@fusyona+web3-core@0.4.14/node_modules/@fusyona/web3-core/dist/lib/config.js:88:21)
    at Object.<anonymous> (/home/mr-papi/Code/work/fusyona/erc1155-factory/hardhat.config.ts:41:38)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/home/mr-papi/Code/work/fusyona/erc1155-factory/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.12.10_typescript@5.4.5/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

**Comment by MakeMake23** [comment]
I'm gonna recheck this and try to add Sei Testnet.
